### ISSUE TITLE
Import des Famille (attribute_set) - Colonne "label" introuvable

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#10]
Lors de test de l'import des familles de produit, pour un akeneo configuré avec uniquement la locale fr_FR, avec le fichier suivant : 
```
code;label-fr_FR;attributes;attribute_as_label;requirements-magento
shirt;T-shirt;sku,name,color,description,price,status,size_shirt,image,manual;sku;sku,name,description,price,status,image
pant;Pantalon;sku,name,color,description,price,status,size_pant,image,manual;sku;sku,name,description,price,status,image
```

J'ai obtenu le message d'erreur suivant : 
> Colinne label introuvable

Hors la colonne label ne peut exister car elle est localisée et est donc suivi du suffix de langue.

Si par contre je modifie le fichier d'import ainsi : 
```
code;label-fr_FR;label;attributes;attribute_as_label;requirements-magento
shirt;T-shirt;T-Shirt;sku,name,color,description,price,status,size_shirt,image,manual;name;sku,name,description,price,status,image
pant;Pantalon;Pant;sku,name,color,description,price,status,size_pant,image,manual;name;sku,name,description,price,status,image
```

l'import se déroule bien

**Comment by spipu** [comment]
Infos Techniques : 
- Debian  Jessie
- Magento CE 2.0.5
- Akeneo EE 1.5.2

**Comment by christophednd** [comment]
Salut Laurent,
Merci pour tes retours, on va regarder ça.
Si de ton coté, tu as une piste ou la solution, n'hésite pas à nous faire un PR ;)
Pimgento2 est volontairement Open source pour que la communauté et des experts techniques  contribuent à son évolution.
à bientôt
Christophe

**Comment by spipu** [comment]
Pour info, lié au format d'export. Il faut utiliser impérativement le format proposé par le bundle EnhancedConnectorBundle.

Je vais faire une issue global pour ce point, et fermer celle-ci
