### ISSUE TITLE
Product Import process takes more time to complete

### ISSUE THREAD

**Issue by gunaziffity** [Agence-DnD/PIMGento-2#106]
We are using pimgento module for magento2.1.4 community version and right now we have 40000 products, 625 attribute sets, 949 attributes, 930 categories.

We can import attribute sets, attributes, options, categories into Magento by using Pimgento module, we could also import the 40000 products with all 949 attribute values into magento but it took around 9 hours to complete the product import process.

Without attributes it took 30-40 mins to import 40000 products, so the problem is in attribute and it's options.

Is there any easy way to import the 40000 products with attributes within an hour?

Can you please help us to optimize and speed up the product import process. Please take it has a priority and resolve this problem.

**Comment by oliverde8** [comment]
Hi, 

I have encountered the same issue with less attributes but a lot of options values.

The more options you have the slower the import gets. We have made a MR #98 that greatly increases the performances of the import in catalogs with a lot of attributes. 

Getting it down within the hour is probably impossible but you should see a great performance improvement.

**Comment by magentix** [comment]
Hi,

MR #98 has been tested, accepted and is available since version 100.2.8. Have you always performance issue with large catalog?
