### ISSUE TITLE
PIMGento Data Import issue

### ISSUE THREAD

**Issue by prabhassharma** [Agence-DnD/PIMGento-2#107]
Hi,

We are working on a new PImgento installation and trying to import data from Akeneo PIM. When doing the import we get the error

> SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'dbuser'@'IP' (using password: YES), query was: LOAD DATA INFILE '/tmp/export_Pimgento_Test_2017-05-27_22-29-25.csv' REPLACE INTO TABLE

As per earlier threads on Github this issue was resolved by granting file permissions to the user, however in our case it cannot be done since our Magento (2.1) and Akeneo both are hosted on amazon servers, which does not allow giving file access.

Any help is highly appreciated.

Thanks.

**Comment by oliverde8** [comment]
Hi, 

In the pimgento configuration change the **Data Insertion method** to `by Rows` instead of `Data In Files`

It should now work without using LOAD DATA INFILE.

**Comment by prabhassharma** [comment]
Hi oliverde8 ,
Thanks for your response.

Can you please confirm that the file that needs to change is `Entities/etc/config.xml`

**Comment by oliverde8** [comment]
Hi,

Not at all, you can change the configuration from the Magento BO, etc/config.xml files contains default values. **You must never modify the code of magento modules you install**. 

If you need to change a behaviour there is always a clean way to do it that does not require editing the source code of other people.

**Comment by prabhassharma** [comment]
Thanks @oliverde8. It works fine now.
