### ISSUE TITLE
Creating Configurable Items in Magento

### ISSUE THREAD

**Issue by prabhassharma** [Agence-DnD/PIMGento-2#108]
Hi,

I am trying to create items in magento using the pimgento import. The simple products work fine, but I am unable to figure how to create configurable and simple relation using PIMGento import.

**In our system we create parent/child relation as below:
The configurable  will look like: MS-XXX-AA0001
The children/simple products under this parent will look like: MS-XXX-AA0001-A01, MS-XXX-AA0001-A02 and so on.**

In Akeneo (CE) we have created an attribute "Parent" using which we are linking the parent & child, so in the product export CSV the relation is maintained.

Any ideas on how this can be achieved in PIMGento import so that MS-XXX-AA0001 is the configurable and the children are linked to it.

Thanks

**Comment by magentix** [comment]
Hi,

For configurable creation in Akeneo, you must use "Variant group" feature. Variant code will be used for configurable SKU, and configurable product data (other than the name) will be setted with first simple product data.

In configuration (**Stores > Configuration > Catalog > Pimgento > Product**), you can add attribute to use with configurable product, picked from first simple product.
