### ISSUE TITLE
Import des attributs - Colonne "families" introuvable

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#11]
Lors de l'import du fichier d'attribut suivant : 

type;code;label-fr_FR;group;unique;useable_as_grid_filter;allowed_extensions;metric_family;default_metric_unit;reference_data_name;localizable;scopable
pim_catalog_identifier;sku;Réf.;default;1;1;;;;;0;0
pim_catalog_text;name;Nom;default;0;1;;;;;1;0
pim_catalog_simpleselect;color;Couleur;color;0;1;;;;;0;0
pim_catalog_textarea;description;Description;default;0;0;;;;;1;0
pim_catalog_price_collection;price;Prix;price;0;0;;;;;0;0
pim_catalog_boolean;status;Status;default;0;0;;;;;0;0
pim_catalog_simpleselect;size_pant;"Taille pantalon";size;0;1;;;;;0;0
pim_catalog_simpleselect;size_shirt;"Taille T-shirt";size;0;1;;;;;0;0
pim_catalog_image;image;Image;media;0;0;jpg;;;;0;0
pim_catalog_file;manual;"Manuel d'Utilisation";media;0;0;pdf;;;;1;0

Il m'est indiqué que la colonne "families" est manquante, alors que dans Akeneo 1.5.2, ce n'est plus le fichier des attributs qui porte le lien avec les familles, mais le fichier des familles qui indique de quelles attributs est constitué une famille.

J'ai utilisé les profils Akeneo natifs suivant : 
Akeneo CSV Connector / Attribute export in CSV
Akeneo CSV Connector / Family export in CSV

**Comment by christophednd** [comment]
Salut Laurent,
Merci pour tes retours, on va regarder ça.
Si de ton coté, tu as une piste ou la solution, n'hésite pas à nous faire un PR ;)
Pimgento2 est volontairement Open source pour que la communauté et des experts techniques  contribuent à son évolution.
à bientôt
Christophe

**Comment by spipu** [comment]
Hello,

je viens de parler avec Benoît (Akeneo), en fait le format attendu par PimGento nécessite d'utiliser le EnhancedConnectorBundle même avec Akeneo 1.5 (malgrès ce que vous indiquez dans la documentation). PimGento ne serait pas compatible pour l'instant avec le format d'export natif d'Akeneo.

Est-ce qu'une compatibilité avec le format natif est prévu dans la roadmap ? Ou conseillez-vous de continuer à utiliser le EnhancedConnectorBundle ? 

merci par avance, 

Laurent - Smile

**Comment by spipu** [comment]
lié au format d'export. Il faut utiliser impérativement le format proposé par le bundle EnhancedConnectorBundle.

Je vais faire une issue global pour ce point, et fermer celle-ci
