### ISSUE TITLE
Configurable products created, image file ignored

### ISSUE THREAD

**Issue by QwertyZW** [Agence-DnD/PIMGento-2#110]
When importing products, the configurable products and their variants are created correctly, but the images for the configurable products are not imported correctly although their paths in the image columns in the akeneo-generated csvs are correct. In other words they match the file structure generated by akeneo which would be in the same folder as the imported csv durring the import procedure.

The 'name' attribute is also not imported, not from the attribute value from the variant group csv nor any of the generated simple product's 'name' attribute (this attribute is simply inherited from the variant group's attribute set)

**Comment by QwertyZW** [comment]
Misconfiguration on my end

**Comment by akosglue** [comment]
how did you solve it?

**Comment by QwertyZW** [comment]
you need to go into the module configuration from the magento2 admin and add the column names as attributes to be imported for configurable products: you have to leave the value field empty though so it's picked up from the column (very unintuitive, although that's what it says in the instructions on that same configuration page)
