### ISSUE TITLE
Question : Is the product removal of old categories missing ?

### ISSUE THREAD

**Issue by Djamy** [Agence-DnD/PIMGento-2#112]
Hi !

I just wanted to ask a quick question about categories assignation.
Is it me or this extension doesn't handle the the removal of categories when importing products ?

In the PimGento-1 it seems to be managed [here](https://github.com/Agence-DnD/PIMGento/blob/master/app/code/community/Pimgento/Product/Model/Import.php#L1100).

Could you, please, give me more details about this ?
Is it a constraint from the Magento2 data model or something else ?

Thank you!

**Comment by magentix** [comment]
Hi,

This feature have not yet been implemented. This will be added.

Regards.

**Comment by Djamy** [comment]
Thanks for the answer.

We'll keep an eye on this then :)
