### ISSUE TITLE
All products are assigend to all website ids

### ISSUE THREAD

**Issue by mvenghaus** [Agence-DnD/PIMGento-2#113]
With 8 stores it is hard when all products are assigned to all websites. I think a better way would be if the website ids are based on the root categories of the product.

Or is there another solution and i don't see it?

**Comment by magentix** [comment]
Hi,

Actually there is no way, products will be assigned automatically on all websites:

https://github.com/Agence-DnD/PIMGento-2/blob/master/Product/Model/Factory/Import.php#L783

I am searching for a solution (root category is maybe the solution).
