### ISSUE TITLE
Incompatibility with EE Staging Content

### ISSUE THREAD

**Issue by joaquin-becerra** [Agence-DnD/PIMGento-2#119]
We are using Magento EE 2.1.14.

When using Magento Content Staging the table:

` catalog_product_entity`

 can contain rows like these
`mysql> select * from catalog_product_entity where entity_id = 3067 order by 3;'

| row_id | entity_id | created_in    |  updated_in | (...)
|   3067 |      3067 |                   1 | 1498746060 | (...)
|   3389 |      3067 | 1498746060 | 1498833660 | (...)
|   3390 |      3067 | 1498833660 | 2147483647 | (...)

Yes!, multiple records by entity_id.

`bin/magento pimgento:import --code=product --file=products.csv`

When we run the update of products of pimgento, so the records are:

| row_id | entity_id | created_in | updated_in 
|   3067 |      3067 |                   1 | **2147483647** | 
|   3389 |      3067 | 1498746060 | 1498833660 |
|   3390 |      3067 | 1498833660 | 2147483647 |

My workarround:

  I run a query to correct the affected 'updated_in' value

`update catalog_product_entity x, ( select min(b.created_in) as min_created_in,  a.row_id as row_id , a.entity_id from catalog_product_entity a, catalog_product_entity b where a.created_in = 1 and a.updated_in = 2147483647 and b.entity_id = a.entity_id and a.row_id < b.row_id  group by a.entity_id ) y set x.updated_in = y.min_created_in where x.row_id = y.row_id;
`

Yes!, an ugly solution

Probably the problem is repeated with other entities such as categories

It would be nice if Pimgento did not modify the 'updated_in' value in these cases.

Regards

**Comment by magentix** [comment]
This has been fixed in last release (100.2.15)
