### ISSUE TITLE
Support du format natif Akeneo 1.5

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#12]
Hello,

Dans le ReadMe, il est indiqué qu'il n'est pas nécessaire d'utiliser le bundle EnhancedConnectorBundle pour le format d'export si Akeneo est en version 1.5

Hors ce n'est pas le cas, PimGento refuse l'import du format CSV natif d'akeneo pour les familles de produit et les attribut produit (je n'ai pas pu essayer les produits).

Il faudrait discuter de la prise en charge du format natif, mais en attendant, je conseillerais de modifier votre ReadMe.

Laurent

**Comment by magentix** [comment]
Salut Laurent,

En effet, entre Akeneo <= 1.4 + EnhancedConnectorBundle et Akeneo 1.5, une différence majeur a eu lieu au niveau des exports des attributs et des familles.

Jusqu'à maintenant, nous importions dans un premier temps les familles, puis les attributs. L'export des attributs nous permettait de lier l'attribut à la famille, grâce à la colonne "families" : 

```csv
type;code;...;families
```

La colonne "families" n'existe plus, mais la liaison entre l'attribut et la famille est maintenant possible avec une nouvelle colonne (attributes) de l'export des familles : 

```csv
code;label-en_US;...;attributes
```

La façon de procéder est donc inversée, il nous faut discuter de ce point en interne (modification Pimgento ou enrichissement des exports Akeneo).

Pour simplifier les choses, les 2 types d'import seront certainement gérés directement dans Pimgento.

Matthieu

**Comment by spipu** [comment]
Hello,

je ne pense pas que ce soit urgent dans l'absolue, étant donné qu'avec le format d'export de EnhancedConnectorBundle cela marche bien.

En attendant, je pense qu'il faudrait juste changer le readme de PimGento pour dire que EnhancedConnectorBundle est toujours nécessaire, même en 1.5, car de toute façon, pour le format du fichier des produits simples, c'est indispensable et parfaitement adapté.

qu'en penses-tu ?

cordialement

Laurent

**Comment by magentix** [comment]
Bonjour Laurent,

Le readme a été modifié suite au MR que tu as proposé.

Merci beaucoup !
