### ISSUE TITLE
Mysql unknown column error during product import when tax classes set

### ISSUE THREAD

**Issue by mveldhuizen** [Agence-DnD/PIMGento-2#125]
Affected version is 100.2.12, 100.2.11 is not affected and works correct for us.

Error during import:
Column not found: 1054 Unknown column ‘2’ in ‘field list’, query was: INSERT INTO `catalog_product_entity_int` (`attribute_id`, `store_id`, `entity_id`, `value`) SELECT 133 AS `attribute_id`, 0 AS `store_id`, `tmp_pimgento_entities_product`.`_entity_id` AS `entity_id`, IF(`2` <> “”, `2`, NULL) AS `value` FROM `tmp_pimgento_entities_product` ON DUPLICATE KEY UPDATE `attribute_id` = VALUES(`attribute_id`), `store_id` = VALUES(`store_id`), `entity_id` = VALUES(`entity_id`), `value` = VALUES(`value`)

This error is produced by 2 things, as far as I know. We have set the default product tax classes in the config settings.
Those are added to the import by this class/code (Pimgento\Product\Model\Factory\Import):
        $taxClasses = $this->_productHelper->getProductTaxClasses();
        if (count($taxClasses)) {
            foreach ($taxClasses as $storeId => $taxClassId) {
                $values[$storeId]['tax_class_id'] = new Expr($taxClassId);
            }
        }

After that the values are set, and this has the following new code (Pimgento\Entities\Model\ResourceModel\Entities::setValues):
        'value'          => new Expr('IF(`' . $value . '` <> "", `' . $value . '`, NULL)'),

We have set the tax_class_id to 2, this results in the query trying to find the column '2' which does not exist.

**Comment by magentix** [comment]
Hi,

This has been fixed in release 100.2.14.

**Comment by mveldhuizen** [comment]
Tested, and bug is indeed fixed
