### ISSUE TITLE
 Column label not found in family import

### ISSUE THREAD

**Issue by Vanitha-Ramkumar** [Agence-DnD/PIMGento-2#126]
Hi,

I have three locale in akeneo (English, German and Spanish). When I try to import the exported CSV file from Akeneo to Pimgento, it shows the below error.

 **_Column label not found_**

code;label-en_US;label-de_DE;label-es_ES;attributes;attribute_as_label;requirements-b2b;requirements-b2c;requirements-ecommerce

Please advise.

**Comment by magentix** [comment]
Hi,

Magento can not translate family name. In Pimgento, 2 columns are required : code and label, without localised (-en_US) data.

So with must update family import for set attribute set name in Magento with admin default language (exemple: en_US) when label is localised.
