### ISSUE TITLE
Images doesn't upload, manual upload doesn't import images

### ISSUE THREAD

**Issue by nwyke** [Agence-DnD/PIMGento-2#129]
Hi

I have problems getting images with the product import.
When I use the backend interface to upload products, no "files" directory is created in the var/import/pimgento folder. On my local machine it exists in the same directory as the products.csv file.
If I manually move the "files" directory to the server, and run the following command, the images is ignored:
`php bin/magento pimgento:import --code=product --file=products.csv`

In Akeneo i have a image attribute with the code "image", and my settings in the backend of Magento is:
<img width="605" alt="skaermbillede 2017-07-08 kl 17 04 57" src="https://user-images.githubusercontent.com/18631644/27986449-ab1a64c0-63ff-11e7-9f8d-627b924c4927.png">

Am I missing something?

Best regards
Nicolaj

**Comment by akosglue** [comment]
any updates?

**Comment by nwyke** [comment]
I paused the magento2 migration project, so no update.

**Comment by NagarajuKasa** [comment]
@Nicolaj 

i am also facing same issue let me know whether you have any idea?

thanks
