### ISSUE TITLE
mauvaise initialisation des stocks des produits simples si plusieurs websites.

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#13]
Bonjour,

Si plus d'un website est paramétré dans Magento (avec un mapping tel que 1 website = 1 channel), l'import de produit n'initialise pas qu'une seule ligne par produit simple dans la table cataloginventory_stock_item, mais initialise une ligne par produit et par website, ce qui engendre par la suite l'erreur suivante dès qu'une collection de produit est chargée avec les données de stock (comme sur la grille des produit en BO par exemple): 

> Item (Magento\Catalog\Model\Product\Interceptor) with the same id "XXX" already exist

le problème semble venir de la méthode Pimgento\Product\Model\Factory\Import::initStock qui boucle sur tous les websites.

Laurent

**Comment by magentix** [comment]
Hi Laurent,

This issue has been fixed in last release (100.0.7).

Regards,
Matthieu

**Comment by spipu** [comment]
thanks !
