### ISSUE TITLE
mauvaise initialisation des stocks des produits configurable

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#14]
Bonjour,

lors de l'import des CSV des variants puis des produits, afin de créer les configurables et les simples dans Magento, l'alimentation de la table cataloginventory_stock_item a été oubliée pour les configurables.

Etant donné qu'aucune ligne n'est enregistrée dans la table, les valeurs par défaut apparaissent dans lors de l'édition des configurables en BO.

![screenshot-demo lxc 2016-05-09 15-43-28](https://cloud.githubusercontent.com/assets/10595905/15114994/fe0d0810-15fc-11e6-9aa7-ef32242c290d.png)

Hors ces valeurs par défaut induise en erreur car Magento a mis par défaut les valeurs "Yes" et pas "Non", et "In Stock" et pas "Out of Stock", du coup on pense que tout est bien configuré, alors qu'en base rien n'est enregistré, et du coup la génération des index n'est pas bonne et indique que le configurable n'est pas en stock, ce qui empêche son affichage en FO.

Il faudrait donc initialiser le stock des produits configurables (lors de leur création uniquement).

Cordialement,

Laurent

**Comment by magentix** [comment]
Hi Laurent,

This issue has been fixed in last release (100.0.7).

Regards,
Matthieu

**Comment by spipu** [comment]
Thanks !
