### ISSUE TITLE
how to enable a product per website/channel?

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#15]
Hi,

this is not a issue, but juste a question.

on a magento with 3 websites (corresponding to 3 channels), how to import product that will be enable on only 2 websites ? is ther a specific mapping to do ? or do we need a specific attribute ?

best regards,

Laurent

**Comment by spipu** [comment]
solved.

the simple way is to create an attribute "status" type int, scopable, and to configure pimgento to link each channel to each website.

The values will be 1=enable and 2=disabled

Laurent

**Comment by julienanquetil** [comment]
CAN you détail a little bit this tricks ? Like enable / disable statuts is not global in magento ?
How do you map it in pimgento ? Thanks

**Comment by julienanquetil** [comment]
ok got it :)
