### ISSUE TITLE
Akeneo 2.0 support

### ISSUE THREAD

**Issue by muspelheim** [Agence-DnD/PIMGento-2#151]
Hi folks, are you planned update codebase for akeneo 2.0?

**Comment by DnD-Tuk** [comment]
Hi @muspelheim!

We will release a roadmap and also a doc for both PIMGento versions next week!
It will answer most of the questions the community can have regarding the future of the connector.

Thanks for your interest in PIMGento and stay tuned!

**Comment by Hocdoc** [comment]
Is there already somewhere the roadmap published? 
I would be interested about Akeneo 2 and Magento 2.2 as we want to update both. Thanks.

**Comment by DnD-Tuk** [comment]
Hello @Hocdoc 

You can find our roadmap here : 

https://github.com/Agence-DnD/PIMGento-2/blob/master/doc/important_stuff/roadmap.md

**Comment by Hocdoc** [comment]
Thank you, this information is very useful for us. :-)

**Comment by muspelheim** [comment]
@DnD-Tuk Hi, any news there?

**Comment by DnD-Tuk** [comment]
Hello @muspelheim ,

We are working on it.
Expect a release soon!

Regards.

**Comment by AminMkh** [comment]
hey there, just wondering if there are any updates, I thought you guys would have a branch for it.

**Comment by akosglue** [comment]
Should be ok now with the update.
However, I can't update to "version": "100.3.0" on my magento 2.1.10 because magento 2.1.10 requires "magento/module-store": "100.1.8", whereas pimgento requires "magento/module-store": "^100.2.1".

**Comment by AminMkh** [comment]
same here, on Magento 2.0 I get the follow:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: magento/module-store[100.2.1, 100.0.9].
    - Can only install one of: magento/module-store[100.2.1, 100.0.9].
    - Can only install one of: magento/module-store[100.0.9, 100.2.1].
    - agencednd/module-pimgento 100.3.0 requires magento/module-store ^100.2.1 -> satisfiable by magento/module-store[100.2.1].
    - Installation request for agencednd/module-pimgento ^100.3 -> satisfiable by agencednd/module-pimgento[100.3.0].
    - Installation request for magento/module-store (locked at 100.0.9) -> satisfiable by magento/module-store[100.0.9].

Installation failed, reverting ./composer.json to its original content.
```

**Comment by magentix** [comment]
Hi,
This has been fixed. You can now proceed to install on Magento < 2.2

Regards,
Matthieu

**Comment by AminMkh** [comment]
just out of curiosity, how do you install pimgento ? I am using composer require as in the documentation, but I have an older copy of it.

This is the composer.json file (vendonr/agencednd/module-pimgento/) and it is not the latest one on the Git repo:
```
{
  "name": "agencednd/module-pimgento",
  "description": "Module Pimgento for Magento 2",
  "require": {
    "php": "^7.0",
    "magento/framework": "^101.0.1",
    "magento/module-backend": "^100.2.1",
    "magento/module-catalog": "^102.0.1",
    "magento/module-eav": "^101.0.0",
    "magento/module-store": "^100.2.1"
  },
  "type": "magento2-module",
  "version": "100.3.0",
  "license": [
    "OSL-3.0",
    "AFL-3.0"
  ],
  "autoload": {
    "files": [
      "Attribute/registration.php",
      "Category/registration.php",
      "Entities/registration.php",
      "Family/registration.php",
      "Import/registration.php",
      "Log/registration.php",
      "Option/registration.php",
      "Product/registration.php",
      "Variant/registration.php",
      "Upgrade/registration.php"
    ],
    "psr-4": {
      "Pimgento\\": ""
    }
  },
  "authors": [
    {
      "name": "Agence DnD",
      "homepage": "http://www.dnd.fr/",
      "role": "Developer"
    }
  ]
}
```

**Comment by AminMkh** [comment]
I am also getting this error:
```
Unknown module(s): 'Pimgento_VariantFamily'
```

When doing:
> php bin/magento module:enable Pimgento_VariantFamily
Which is probably due to the older code in my installation

**Comment by akosglue** [comment]
`composer update`
succeeded for me. 
`Updating agencednd/module-pimgento (100.2.23 => 100.3.0)`

Then I enabled Pimgento_Upgrade for magento.
The setup:upgrade didn't succeed.
`Class Magento\Framework\DB\FieldDataConverterFactory does not exist`

Afterwards I disabled Pimgento_Upgrade and setup:upgrade succeeded.
I can't enable Pimgento_VariantFamily either.

**Comment by magentix** [comment]
Hi,
Yes, Pimgento_Upgrade is only required for migration from Magento 2.1 to Magento 2.2

What message do you have when activating Pimgento_VariantFamily ?

**Comment by akosglue** [comment]
Hi, I get this:
Unknown module(s): 'Pimgento_VariantFamily'

`-sh-4.2$ cat magento2/vendor/agencednd/module-pimgento/composer.json 
{
  "name": "agencednd/module-pimgento",
  "description": "Module Pimgento for Magento 2",
  "require": {
    "php": "^7.0",
    "magento/framework": ">=100.0.1",
    "magento/module-backend": ">=100.0.1",
    "magento/module-catalog": ">=100.0.1",
    "magento/module-eav": ">=100.0.1",
    "magento/module-store": ">=100.0.1"
  },
  "type": "magento2-module",
  "version": "100.3.0",
  "license": [
    "OSL-3.0",
    "AFL-3.0"
  ],
  "autoload": {
    "files": [
      "Attribute/registration.php",
      "Category/registration.php",
      "Entities/registration.php",
      "Family/registration.php",
      "Import/registration.php",
      "Log/registration.php",
      "Option/registration.php",
      "Product/registration.php",
      "Variant/registration.php",
      "Upgrade/registration.php"
    ],
    "psr-4": {
      "Pimgento\\": ""
    }
  },
  "authors": [
    {
      "name": "Agence DnD",
      "homepage": "http://www.dnd.fr/",
      "role": "Developer"
    }
  ]
}
`

**Comment by rainmikko** [comment]
Any update on this?

I also got error message "Unknown module(s): 'Pimgento_VariantFamily'" when I tried to activate that module. My `vendor/agencednd/module-pimgento/composer.json`file looks like this:
```json
{
  "name": "agencednd/module-pimgento",
  "description": "Module Pimgento for Magento 2",
  "require": {
    "php": "^7.0",
    "magento/framework": ">=100.0.1",
    "magento/module-backend": ">=100.0.1",
    "magento/module-catalog": ">=100.0.1",
    "magento/module-eav": ">=100.0.1",
    "magento/module-store": ">=100.0.1"
  },
  "type": "magento2-module",
  "version": "100.3.0",
  "license": [
    "OSL-3.0",
    "AFL-3.0"
  ],
  "autoload": {
    "files": [
      "Attribute/registration.php",
      "Category/registration.php",
      "Entities/registration.php",
      "Family/registration.php",
      "Import/registration.php",
      "Log/registration.php",
      "Option/registration.php",
      "Product/registration.php",
      "Variant/registration.php",
      "Upgrade/registration.php"
    ],
    "psr-4": {
      "Pimgento\\": ""
    }
  },
  "authors": [
    {
      "name": "Agence DnD",
      "homepage": "http://www.dnd.fr/",
      "role": "Developer"
    }
  ]
}
```
I even tried to add that `"VariantFamily/registration.php"` line manually to `vendor/agencednd/module-pimgento/composer.json` and runned `composer dump-autoload`.

Still unable to activate this Pimgento_VariantFamily.

My Magento version is 2.1.8

Any help?

**Comment by akosglue** [comment]
any updates on this ?

**Comment by magentix** [comment]
Hi,

This has been fixed in 100.3.1 release.

**Comment by akosglue** [comment]
Hi, thanks for the info, I have just installed it.
`php bin/magento module:enable Pimgento_VariantFamily`
and then:
The following modules have been enabled:
- Pimgento_VariantFamily
Enabling was successfull, thanks.

**Comment by rainmikko** [comment]
Hi,

I upgraded to 100.3.1 and Pimgento_VariantFamily successfully enabled. Thanks @magentix!
