### ISSUE TITLE
Configurable product name from variant label

### ISSUE THREAD

**Issue by guillaume-netapsys** [Agence-DnD/PIMGento-2#153]
Hello,

My request is not really about an issue but a question.

In my Akeneo, I have some variant groups with code and labels defined.
When I first import my variants and products in Magento, my newly created products appeared without a name.
So I have created a configurable mapping with attribute => "name" and value empty.
Now my configurable name is the name of the first product associated to the variant.

I'm currently looking for the way to configure Magento in order to use variant label (in Akeneo) as configurable name (in Magento 2). I can't find any documentation about it, so is it possible to do this ?

Thanks in advance.
Guillaume.

**Comment by DnD-Tuk** [comment]
Hello @guillaume-netapsys ,

You could set an attribute name in Akeneo in your variant group.
Products in this variant group will inherit the value so PIMGento can import this value for your configurable.

Does this answer your question?

Thanks for your interest in PIMGento!

**Comment by guillaume-netapsys** [comment]
Hello @DnD-Tuk 

Thank you for your quick answer.
Right I missed this feature in Akeneo variant panel.

Is the attribute code "name" mandatory ?
My product names are stored in a "designation"  attribute and I'm using a mapping designation > name for simple product. Do I need to create a similar mapping for configurable ?

Thank you.
Guillaume.

**Comment by DnD-Tuk** [comment]
Guillaume,

It was just an example since I didn't know the code nor the label of your attribute :).

You can use your own "designation" attribute the same way in the variant group, just add it and it will be inherited by your products in it.

Then keep your mapping in PIMGento.

Regards.

**Comment by guillaume-netapsys** [comment]
Benjamin,

Oh ok it seems really clear now, and very easy to use.
In my words, configurable products are products after all, so after creation from the variants, my variant designation will be mapped as configuration name with the classic attribute mapping, not the configurable one.

Perfect ! Thank you very much to provide me a complete and quick answer !

Best regards !
Guillaume.

**Comment by DnD-Tuk** [comment]
You'r welcome!
