### ISSUE TITLE
How to import automatically new files ?

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#16]
Hi,

this is not a issue, but juste a question.

on Pimgento for Magento 1, there was lots (and very useful) of configurations about crons to import automatically new files for each profiles.

on Pimgento for Magento 2, i do not find it. Is it in the roadmap ?

best regards,

Laurent

**Comment by magentix** [comment]
Hi Laurent,

With Pimgento 2, you can configure Cron rules directly from server, with new rule from command line tool, example:

```shell
php bin/magento pimgento:import --code=product --file=product.csv
```

Available codes are:

* category
* family
* attribute
* option
* variant
* product

Regards,
Matthieu

**Comment by spipu** [comment]
OK, thanks.
