### ISSUE TITLE
Translated category import from akeneo 2.1.1 to magento 2.2.2 - no translation

### ISSUE THREAD

**Issue by akosglue** [Agence-DnD/PIMGento-2#166]
Hello,

I would like to report an issue about pimgento 2.
This is my setup:
- fresh install of magento 2.2.2
- setup 3 store views in the same store for multiple languages with code: en_US, nl_BE, fr_BE
- category tree created in akeneo, with 3 locales, en_US, nl_BE, fr_BE, categories are translated
- install pimgento 100.3.1
- import categories to magento from akeneo with the UI
- categories are not translated in magento. what I would expect is that if I change the store view in magento, i get the translated category name (that one from akeneo)

Can anyone take a look at this?

**Comment by dnd-derwent** [comment]
Hello akosglue,

I tried to reproduce your issue on a fresh install of magento 2.2.2 with 3 store views in the same store with languages : en_US, de_DE and fr_FR.
I used the sample data from Akeneo 2.1.
After importing the categories in Magento, their names are translated on the different store views.

Did you configure the language for each store view in Magento (in Stores > Configuration > General > Locale Options > Locale) ?

**Comment by akosglue** [comment]
Hi, thanks for the update, I will re-test it, when I get there with my planning :)

**Comment by akosglue** [comment]
Hi, I can confirm that I could successfully import the translated category names. I think I misconfigured the locales in Magento. It is important to have the exact matching between the akeneo and the magento locales.

**Comment by akosglue** [comment]
I close this because of misconfiguration on my side.
