### ISSUE TITLE
bad pim type for price attribute

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#17]
hi,

in the Attribute Type helper, the given pim type for price is "pim_catalog_price" : 

https://github.com/Agence-DnD/PIMGento-2/blob/master/Attribute/Helper/Type.php#L29

but in the fixtures, it is "pim_catalog_price_collection" : 

https://github.com/Agence-DnD/PIMGento-2/blob/master/Attribute/fixtures/attribute.csv#L27

What is the good attribute type to use ?

Best Regards,

Laurent

**Comment by magentix** [comment]
Hi Laurent,

Default price type has been renamed in last release (100.0.7).

For custom Pim type, you can configure it in Pimgento configuration:

Stores > Configuration > Catalog > Pimgento > Attributes > Additional types

Regards,
Matthieu

**Comment by spipu** [comment]
thanks !
