### ISSUE TITLE
related/cross-sell/upsell models are ignored

### ISSUE THREAD

**Issue by akosglue** [Agence-DnD/PIMGento-2#178]
Hello,
I provide here the steps to reproduce the issue.
1. Create 2 product models (productA and productB), create a few variants for each model.
2. Edit productA with bulk actions and associate to productB with related products association.
3. Edit productB with bulk actions and associate to productA with cross-sell products association.
4. Import products and models to Magento 2.
5. Related and cross-sell links are not created in magento.

I think the problem is that the 'related-product_models' column is ignored and only the 'related-products' is processed. Similarly, for the X_SELL columns, product_models is ignored.

Edit: also, if I take a look at the feature commit: https://github.com/Agence-DnD/PIMGento-2/commit/893b7831e11b5b5e07e3fd1a05cca1d73e9c47d6

I see that the associated product_models are not even processed. Only the products column.

**Comment by dnd-derwent** [comment]
HI @akosglue 

This issue has been fixed in 100.3.3
