### ISSUE TITLE
Configurable product : status has no value

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#18]
Hi,

when creating a simple product, it is automatically enabled.

when creating a configurable product, it is not, and the "status" attribute has no value in the catalog_product_entity_int table.

is it normal (we have to activate it manually), or is it a bug ?

**Comment by spipu** [comment]
i have maybe a solution : set the status from the simple product, but i have found the issue #19 when testing the solution.

**Comment by magentix** [comment]
Hi,

Indeed, add "status" attribute in "Configurable" configuration option is a solution. Value will be taken from simple product.

However, we will add a default configurable value option like Pimgento for Magento 1. This will be a more confortable solution.

**Comment by spipu** [comment]
ok thanks.

**Comment by magentix** [comment]
Hi,

This has been added in last release (100.0.9).

It is now possible for configurable to force value, or to get value from simple product.

After update, run "php bin/magento setup:upgrade" for upgrade.

**Comment by spipu** [comment]
thanks for this new release
