### ISSUE TITLE
Scopable attribute: not work for configurable

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#19]
Hi !

i try to use the "pimgento/product/configurable_attributes" configuration with a scopable attribute

it was to find a solution on the issue #18 by using a scopable attribute status like explain in #15 .

But is seems that this configuration does not work with scopable attribute. It works only with localizable attribute.

We can see it in the code : https://github.com/Agence-DnD/PIMGento-2/blob/master/Product/Model/Factory/Import.php#L190

Best Regards,

Laurent

**Comment by magentix** [comment]
Hi,

This issue has been fixed in commit e8d4bb7 with all suffix case:

* en_US
* channel
* channel-en_US
* USD
* channel-USD
* en_US-channel-USD

**Comment by spipu** [comment]
Thx !
