### ISSUE TITLE
Akeneo 1.5 support

### ISSUE THREAD

**Issue by Hocdoc** [Agence-DnD/PIMGento-2#2]
First of all I want to say thank you for releasing PIMGento-2! :-)

The README says, PIMGento-2 supports Akeneo 1.3+1.4.

As the EnhancedConnectorBundle is now also available for Akeneo 1.5 and nothing big has changed in the CSV output between 1.4->1.5, I think that PIMGento-2 should also work with Akeneo 1.5?

If this is true, maybe you could add V. 1.5 in the README as many new users want to use the newest Akeneo version.

**Comment by SirBigoo** [comment]
I just try with Aekeno 1.5 demo version data and Enhanced Connector plugin, and it works. All imports are ok.
There is one problem with a product (I got it with 1.4 export csv too) : it has category with 0 as id, so I got  Integrity constraint violation error in SQL. I guess it is demo data that is corrupted.
I removed this product from csv export (sku = AKNSTK) and it's ok.

So you can add Akeneo V1.5 it to the README :-)

**Comment by magentix** [comment]
Hi,

Thank you very much for tests. Akeneo 1.5 support will be added to readme file :)
