### ISSUE TITLE
Not compatible with M 2.3

### ISSUE THREAD

**Issue by TonySma** [Agence-DnD/PIMGento-2#207]
### Environment and configuration
PHP 7.1
Magento 2.3
PIMGento 2 API (newest version)

### Steps to reproduce
Import categories (or other entities)

### Expected result
Import sucessfully

### Actual result
An error appears: [06:57:59] Notice: Undefined index: VARCHAR(255) NOT NULL DEFAULT "

### Background:
In M 2.3 there is a new method in Magento\Framework\DB\Adapter\Pdo\Mysql::addColumn() which automatically parses the schema (SchemaListener), so you don't need to define it
The PIMGento 2 module allows working with M 2.3 (in composer.json)

**Comment by Hocdoc** [comment]
I am not a maintainer but want to thank you for the PR. :-)

Unfortunately I think there will be no big changes anymore in PIMGento-2-CSV as Agence-DnD is developing [PIMGento-2-API](https://github.com/Agence-DnD/PIMGento-2-API) which claims to already support M2.3.

Our company would prefer to stay with the CSV importer as this is much more flexible than the new API approach for us.

**Comment by Dnd-Gimix** [comment]
Hello @TonySma , @Hocdoc ,

We have released Magento 2.3 compatibility in the new 100.4.0 release.

Thanks again for the contribution.
Have a nice day !

Regards,
