### ISSUE TITLE
Metric attributes

### ISSUE THREAD

**Issue by Atomschinken** [Agence-DnD/PIMGento-2#25]
When trying to import a metric type attribute from Akeneo only the unit is imported, not the value.

Example:
We have a metric attribute named "insulation". The csv has this columns:
insulation	insulation-unit
50.0000	MILLIMETER

Because PIMGento2 finding the colum prefix like this: `$columnPrefix = explode('-', $column);`
only the last column with the same beginning is used as value source.

Best solution IMO would be to combine the value and unit into one attribute field during import (in our example named "insulation"). Alternatively the unit could be saved in a seperate attribute.

Please correct me if i'm missing anything here :)

**Comment by magentix** [comment]
Hi,

Thanks for report. I will begin to work on this issue :)

**Comment by magentix** [comment]
Hi,

This issue will be fixed in next release: 100.0.10

Development starts on 2016-06-02

**Comment by magentix** [comment]
Hi,

Issue has been fixed in last release (100.0.10).

**Comment by Atomschinken** [comment]
Hi,

i just tested it and it works fine except one little issue:
The unit is now dropped during the import. In our case the unit is displayed together with the value (e.g. "120 kg") so it is needed.

The only solution i'm thinking of right now is to add another attribute with the unit. But it just doesn't feel right to maintain the unit in Akeneo AND Magento ;)

Maybe you can give me a hint

**Comment by magentix** [comment]
Hi @Atomschinken

The only solution is to create a new attribute with the unit, who will be created with "attribute" import, and filled with "product" import.
