### ISSUE TITLE
Attribute label duplicates

### ISSUE THREAD

**Issue by Atomschinken** [Agence-DnD/PIMGento-2#26]
When reimporting the attributes, the labels are duplicated.
In the table "eav_attribute_label" there are several entries for the same attribute_id:
424	132	0	Headline
425	132	1	Headline
562	132	0	Headline
563	132	1	Headline
5	132	1	Headline
6	132	0	Headline
147	132	0	Headline
148	132	1	Headline
286	132	0	Headline
287	132	1	Headline

This results in exceptions in the frontend:
Item (Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor) with the same id "90" already exist

Any ideas?

**Comment by magentix** [comment]
Hi,

Problem is on store label import (**addAttributes** method).

There is no unique key on "attribute_id", "store_id" combinaison.

I will fix this issue with test on existing combinaison.

**Comment by magentix** [comment]
Hi,

This issue will be fixed in next release: 100.0.10

Development starts on 2016-06-02

**Comment by magentix** [comment]
Hi,

Issue has been fixed in last release (100.0.10).

**Comment by Atomschinken** [comment]
Looks good to me. Thank you.
