### ISSUE TITLE
How to update stock level?

### ISSUE THREAD

**Issue by Atomschinken** [Agence-DnD/PIMGento-2#27]
I've tried different attribute codes in Akeneo but nothing happens:
quantity_and_stock_status
is_in_stock

How can i import a stock level from Akeneo to Magento2?
Maybe this needs some sort of attribute mapping?

Any help would me much appreciated.

**Comment by spipu** [comment]
For me, a PIM does not have to manage stock...

**Comment by magentix** [comment]
Hi,

Indeed, we have not done a stock import from the pim. This can be developped with specific developpment (**initStock** override from **Pimgento\Product\Model\Factory\Import**.

**Comment by clicktrend** [comment]
You can easily use the native import mechanism of magento 2
