### ISSUE TITLE
pimgento2 create configurable products

### ISSUE THREAD

**Issue by ntorras** [Agence-DnD/PIMGento-2#28]
Hi,
I have tried several times to import products csv file that contains some configurable products, but I can't manage to create them as configurables, they are always created as simple products. I think I'm missing something but I don't know what.
The Pimgento2 configurations are very simple, so I guess that the problem can be in the csv file structure or maybe with the variants file.

Variants file is just:
code;axis;label;type
accessories_se_variation;sap_material_description;accessories se variations;VARIANT

What I have seen is that in my products file the column groups is empty, is that ok?

Thanks for your help

**Comment by magentix** [comment]
Hi,

For configurable, **groups** column must not be empty. We add configurable product with this data. **groups** column match with **code** column in **pimgento_variant** table.

Are products configured for groups in pim?

**Comment by ntorras** [comment]
Hi,

The file for variants that we were using was not ok, that's why configurable products were not created. The problem that we are having now is that the configurable is not related with the simple products, but we have localized the problem, we have seen that the axis that we are using is a text camp, and magento do not allowing us to use this kind of attribute

It would have been very usefull to have a manual or something to know exactly the files format and how to generete them in akeneo.

Regards

 
    Núria Torras
 e-commerce specialist
 Web Applications Development
 
 Tel. (+34) 93 379 40 29 
 E-mail: ntorras@asmws.com / Skype id: n.torras.h
 C/ Solsonès 2, Edifici B, 2º C3 - Parc de Negocis MAS BLAU
 08820 El Prat de Llobregat - Barcelona (Spain) 
 www.asmws.com   

-----Matthieu Vion <notifications@github.com> escribió: -----
Para: Agence-DnD/PIMGento-2 <PIMGento-2@noreply.github.com>
De: Matthieu Vion <notifications@github.com>
Fecha: 27/05/2016 15:30
Cc: ntorras <ntorras@asmws.com>, Author <author@noreply.github.com>
Asunto: Re: [Agence-DnD/PIMGento-2] pimgento2 create configurable products (#28)

Hi,
  For configurable, groups column must not be empty. We add configurable product with this data. groups column match with code column in pimgento_variant table.
  Are products configured for groups in pim?
  —
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
 
 
          


P Antes de imprimir este mensaje, asegúrese de que es necesario. El medio ambiente es cosa de todos.
AVISO DE CONFIDENCIALIDAD
Este mensaje se dirige exclusivamente a su destinatario y puede contener información privilegiada o confidencial. Si no es vd. el destinatario indicado, queda notificado de que la utilización, divulgación y/o copia sin autorización está prohibida en virtud de la legislación vigente. Si ha recibido este mensaje por error, le rogamos que nos lo comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain information that is CONFIDENTIAL and protected by professional privilege. If you are not the intended recipient you are hereby notified that any dissemination, copy or disclosure of this communication is strictly prohibited by law. If this message has been received in error, please immediately notify us via e-mail and delete it.

**Comment by magentix** [comment]
Hi,

For Akeneo sample files, you can open CSV files in **fixtures** directory for each module:

* Variant/fixtures/variant.csv
* Product/fixtures/product.csv
* ...

This will help you to get correct files format to export with Akeneo.
