### ISSUE TITLE
Encoding UTF-8 when import from file

### ISSUE THREAD

**Issue by SirBigoo** [Agence-DnD/PIMGento-2#3]
Hi,

I got and encoding problem when I import csv with special chars (such as ê é à ...).
Can you add an option for specify file encoding ? Default isn't UTF-8 I guess.

The problem is with query like this one :
```
LOAD DATA INFILE 'myFile' REPLACE
INTO TABLE myTable
...
```

I tried to add ```CHARACTER SET UTF8```  after ```INTO TABLE``` and it worked.

Thanks.

**Comment by magentix** [comment]
Hi,

Character set must be UTF8 by default. ```CHARACTER SET UTF8``` have been added after ```INTO TABLE```
