### ISSUE TITLE
about roadmap

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#33]
Hi !

about the following 2 points in the roadmap : 
- Image files import
- Link related products (related, cross-sells, up-sells)

how can we (Smile) participate ? can we work on the linked related products (bases on what you have done in Pimgento1) ?

**Comment by magentix** [comment]
Hi,

Pimgento 2 is a collaborative extension. You can work on related products, and propose all things you need and usefull for community :smile:

We accept MR with pleasure.

**Comment by spipu** [comment]
done for linked products !

https://github.com/Agence-DnD/PIMGento-2/pull/34

but i forgot to modify the roadmap in the readme, sorry...

for the "image files import" part, have you start it ? or can we start on our side ?

Laurent - Smile

**Comment by magentix** [comment]
Thanks a lot @spipu 

#34 has been merged, a new release will be available soon.

We have no already start image files import. We must discuss with team for start date.

**Comment by spipu** [comment]
ok.

If you want, i can put someone on it monday on my side.

**Comment by chrey** [comment]
Hi, 

Do you have more information about media import roadmap now ? We are also going to need it on another project so we need to know if you plan to develop it during the next weeks or not. 

Thanks a lot,

Charlotte

**Comment by Raphael-johanne** [comment]
Hi,

Do you have more information about media import roadmap now ? Are you working on it or it is not in the roadmap ? 

Thanks in advance !

Raphael

**Comment by spipu** [comment]
there was performance issue in the related product import. Now, it is x4 faster

Example: for 50,000 product, with 2 related per products, it was taking 17 minutes. Now it takes 4 minutes.

https://github.com/Agence-DnD/PIMGento-2/pull/60

Now, we are working on the media import

**Comment by spipu** [comment]
The media import can be merged : https://github.com/Agence-DnD/PIMGento-2/pull/62
