### ISSUE TITLE
Compatibility with Magneto EE 2.1

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#38]
Hi,

on Magento EE 2.1 RC3, they have added some staging functionality. The pb is that when the staging module is active (it is possible to upgrade to the EE 2.1 version without installing it), it changes all the database structure for products, categories, and others...

more info here: http://devdocs.magento.com/guides/v2.0/release-notes/backward-incompatible-changes-2.1.html

For example, the entity_id field of all the sub tables catalog_product_entity_* does not exists any more, and a new field "row_id" has been added...

=> Pimgento will not be compatible with EE 2.1 + Staging

I think it will be a good think to add a warning on the readme to say that it is not compatible with the "staging" module of Magento EE 2.1 for the moment.

What do you think about it ?

Laurent

**Comment by magentix** [comment]
Hi laurent,

Readme has been updated.

**Comment by spipu** [comment]
thanks,

i close this issue

**Comment by joshuaswarren** [comment]
Quick question - do you have plans of ever supporting databases where EE 2.1 Staging is already present? All new Magento 2 projects now are starting on 2.1, and most don't realize they should consider turning Staging off so that they can use this awesome Akeneo PIM integration you've built.

**Comment by DanGarner** [comment]
+1 for @joshuaswarren comment.
