### ISSUE TITLE
Multiple attribute mapping conflict

### ISSUE THREAD

**Issue by SirBigoo** [Agence-DnD/PIMGento-2#4]
Hi,

I got a bug when I try to use multiple attribute mapping with the same pim code. I want to set the same image (field image in my csv) to thumbnail, small_image and image attribute in Magento 2.

So I apply this mapping :  

![fields](https://cloud.githubusercontent.com/assets/17948077/14459457/5d7288de-00b8-11e6-8b79-2feba033702c.jpg)

In that example, the ```tmp_pimgento_entities_product``` table created by the import doesn't have all fields that I want.
We only had the field image and thumbnail. It seems that the module take only the last attribute mapped. I tried to change the name of pim column, and my field ```small_image``` was in the table.

I search why in the code, and I guess it is when we add product required data. More precisely, in file ```Product/Model/Factory/Import.php```, function ```addRequiredData()```.
I did not go further in my search.

Is it possible to fix it ?
Thanks a lot.

**Comment by magentix** [comment]
Hi SirBigoo,

I have fixed this issue in new release (100.0.3).

Thanks for report.
