### ISSUE TITLE
forgot a "use" in a class

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#40]
This bug is coming from the pull request 34, i forgot to add this line:

`use \Magento\Framework\DB\Adapter\AdapterInterface;`

on the file https://github.com/Agence-DnD/PIMGento-2/blob/master/Product/Model/Factory/Import.php#L15

because we use it here https://github.com/Agence-DnD/PIMGento-2/blob/master/Product/Model/Factory/Import.php#L918

i'm sorry for this mistake :(

**Comment by magentix** [comment]
Hi,

This has been added in new release :smile: (100.0.12)

**Comment by spipu** [comment]
thanks !
