### ISSUE TITLE
Multiselect attributes

### ISSUE THREAD

**Issue by Atomschinken** [Agence-DnD/PIMGento-2#41]
Hi,

when trying to import a multiselect attribute only the first value is selected.

Example:
An multiselect attribute with the possible values "value1", "value2", "value3", "value4", "value5", "value6"
For the product the according column looks like this: value1,value2,value3

After the import only value1 is selected for the product.

Any ideas?

**Comment by magentix** [comment]
Hi @Atomschinken 

We will look tomorrow to fix this problem.

**Comment by magentix** [comment]
Hi,

This has been fixed in release 100.0.13
