### ISSUE TITLE
Can't install on Magento2.1.0

### ISSUE THREAD

**Issue by HirokazuNishi** [Agence-DnD/PIMGento-2#42]
I just tried to install this extension against Magento 2.1.0, but composer returned these errors blow.

> Problem 1
>     - Conclusion: don't install agencednd/module-pimgento 100.0.12
>     - Conclusion: don't install agencednd/module-pimgento 100.0.11
>     - Conclusion: don't install agencednd/module-pimgento 100.0.10
>     - Conclusion: don't install agencednd/module-pimgento 100.0.9
>     - Conclusion: don't install agencednd/module-pimgento 100.0.8
>     - Conclusion: don't install agencednd/module-pimgento 100.0.7
>     - Conclusion: don't install agencednd/module-pimgento 100.0.6
>     - Conclusion: don't install agencednd/module-pimgento 100.0.5
>     - Conclusion: don't install agencednd/module-pimgento 100.0.4
>     - Conclusion: don't install agencednd/module-pimgento 100.0.3
>     - Conclusion: don't install agencednd/module-pimgento 100.0.2
>     - Conclusion: don't install agencednd/module-pimgento 100.0.1|remove magento/framework 100.1.0
>     - Conclusion: don't install agencednd/module-pimgento 100.0.1|don't install magento/framework 100.1.0
>     - Installation request for agencednd/module-pimgento ^100.0 -> satisfiable by agencednd/module-pimgento[100.0.1, 100.0.10, 100.0.11, 100.0.12, 100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
>     - agencednd/module-pimgento 100.0.1 requires magento/framework 100.0.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
>     - Can only install one of: magento/framework[100.1.0, 100.0.2].
>     - Can only install one of: magento/framework[100.1.0, 100.0.3].
>     - Can only install one of: magento/framework[100.1.0, 100.0.4].
>     - Can only install one of: magento/framework[100.1.0, 100.0.5].
>     - Can only install one of: magento/framework[100.1.0, 100.0.6].
>     - Can only install one of: magento/framework[100.1.0, 100.0.7].
>     - Can only install one of: magento/framework[100.1.0, 100.0.8].
>     - Can only install one of: magento/framework[100.1.0, 100.0.9].
>     - Installation request for magento/framework (locked at 100.1.0) -> satisfiable by magento/framework[100.1.0].

composer.json of this repository specifies "100.0.*" for magento/framework, but 2.1.0 uses "100.1.*".

**Comment by magentix** [comment]
Hi @HirokazuNishi,

Composer.json has been updated. Can you retry to install ?

**Comment by HirokazuNishi** [comment]
@magentix I tried to install it with "composer require agencednd/module-pimgento", but packagist.org returned old composer.json. Therefore I tried "composer require agencednd/module-pimgento@dev-master" and the extension was successfully installed.

Thank you :)

**Comment by magentix** [comment]
Hi,

Last releast (100.1.0) can be easyer installed on Magento 2.1 :)

**Comment by magewn** [comment]
Hi, 
I am same issue with Magento2.1. Below is the error I am getting,
Problem 1
    - Conclusion: don't install magewn/wnpayment dev-master
    - Conclusion: don't install magewn/wnpayment dev-master|remove magento/framework 100.1.3
    - Conclusion: don't install magewn/wnpayment dev-master|don't install magento/framework 100.1.3
    - Installation request for magewn/wnpayment dev-master -> satisfiable by magewn/wnpayment[dev-master].
    - magewn/wnpayment dev-master requires magento/framework 100.0.* -> satisfiable by magento/framework[100.0.10, 100.0.11, 100.0.12, 100.0.13, 100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
    - Can only install one of: magento/framework[100.1.3, 100.0.10].
    - Can only install one of: magento/framework[100.1.3, 100.0.11].
    - Can only install one of: magento/framework[100.1.3, 100.0.12].
    - Can only install one of: magento/framework[100.1.3, 100.0.13].
    - Can only install one of: magento/framework[100.1.3, 100.0.2].
    - Can only install one of: magento/framework[100.1.3, 100.0.3].
    - Can only install one of: magento/framework[100.1.3, 100.0.4].
    - Can only install one of: magento/framework[100.1.3, 100.0.5].
    - Can only install one of: magento/framework[100.1.3, 100.0.6].
    - Can only install one of: magento/framework[100.1.3, 100.0.7].
    - Can only install one of: magento/framework[100.1.3, 100.0.8].
    - Can only install one of: magento/framework[100.1.3, 100.0.9].
    - Installation request for magento/framework == 100.1.3.0 -> satisfiable by magento/framework[100.1.3].

I will appreciate your help !! 

Thanks,

**Comment by rezeyle** [comment]
I'm facing the same problem. Can someone please help?

My Magento is 2.1.3

Error:

myuser@domain [~/public_html]# composer require flowecommerce/pt_br
Using version ^100.0 for flowecommerce/pt_br
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for flowecommerce/pt_br ^100.0 -> satisfiable by flowecommerce/pt_br[100.0.1].
    - Conclusion: remove magento/framework 100.1.3
    - Conclusion: don't install magento/framework 100.1.3
    - flowecommerce/pt_br 100.0.1 requires magento/framework 100.0.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.0.10, 100.0.11, 100.0.12, 100.0.13, 100.0.14, 100.0.15].
    - Can only install one of: magento/framework[100.1.3, 100.0.2].
    - Can only install one of: magento/framework[100.1.3, 100.0.3].
    - Can only install one of: magento/framework[100.1.3, 100.0.4].
    - Can only install one of: magento/framework[100.1.3, 100.0.5].
    - Can only install one of: magento/framework[100.1.3, 100.0.6].
    - Can only install one of: magento/framework[100.1.3, 100.0.7].
    - Can only install one of: magento/framework[100.1.3, 100.0.8].
    - Can only install one of: magento/framework[100.1.3, 100.0.9].
    - Can only install one of: magento/framework[100.1.3, 100.0.10].
    - Can only install one of: magento/framework[100.1.3, 100.0.11].
    - Can only install one of: magento/framework[100.1.3, 100.0.12].
    - Can only install one of: magento/framework[100.1.3, 100.0.13].
    - Can only install one of: magento/framework[100.1.3, 100.0.14].
    - Can only install one of: magento/framework[100.1.3, 100.0.15].
    - Installation request for magento/framework (locked at 100.1.3) -> satisfiable by magento/framework[100.1.3].


Installation failed, reverting ./composer.json to its original content.
