### ISSUE TITLE
Enclosure and Delimiter problem

### ISSUE THREAD

**Issue by tebinu** [Agence-DnD/PIMGento-2#43]
If the delimiter and the enclosure from the export file is not a static default, importing the CSV file is not possible.

Of course one could edit the config, but it would be much better to  have an item in the backend for that.

**Comment by magentix** [comment]
Hi,

This is possible with **Stores > Configuration > Catalog > Pimgento > General**

- CSV: line ending
- CSV: delimiter
- CSV: enclosure
