### ISSUE TITLE
Cannot add or update a child row

### ISSUE THREAD

**Issue by tebinu** [Agence-DnD/PIMGento-2#51]
First import.. a CSV file with 13 rows. No product gets imported

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`catalog_product_entity`, CONSTRAINT `CAT_PRD_ENTT_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_s

**Comment by spipu** [comment]
Look at the issue #50 it will help you :)

**Comment by tebinu** [comment]
oh yes, thanks
