### ISSUE TITLE
doctrine/migrations error during install

### ISSUE THREAD

**Issue by tjuola** [Agence-DnD/PIMGento-2#52]
I’m trying to create demo environment with Akeneo CE 1.5 and Magento 2.1 CE by using Pimgento.
I get this weird error message at the end of installation process:
ubuntu@ip-172-31-46-149:/var/www/html/pim-community-standard$ sudo php composer.phar require akeneo-labs/pim-enhanced-connector:~1.2
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - akeneo/pim-community-dev v1.5.5 requires doctrine/migrations 1.0.0-alpha3@alpha -> satisfiable by doctrine/migrations[v1.0.0-alpha3].
    - akeneo/pim-community-dev v1.5.5 requires doctrine/migrations 1.0.0-alpha3@alpha -> satisfiable by doctrine/migrations[v1.0.0-alpha3].
    - Removal request for doctrine/migrations == 1.0.0.0-alpha3
    - Installation request for akeneo/pim-community-dev (locked at v1.5.5) -> satisfiable by akeneo/pim-community-dev[v1.5.5].

Installation failed, reverting ./composer.json to its original content.
ubuntu@ip-172-31-46-149:/var/www/html/pim-community-standard$

**Comment by spipu** [comment]
For me it is not a pimgento issue, because the pb is on the composer.json file of akeneo, not in Magento.
