### ISSUE TITLE
Import button does not work

### ISSUE THREAD

**Issue by nzidol** [Agence-DnD/PIMGento-2#53]
Hi,

Sort of works for me but some small snags....
After some research it appears the file input element is sized at 1000x1000 and overlaps the button, which means when you think you are pressing the import button you actually are clicking again on the file input. 

![image](https://cloud.githubusercontent.com/assets/13618973/17988387/0d6d812c-6b7a-11e6-8d04-fbc79e7d59a2.png)
Have not had much luck with trying to resize the input or changing the z-order. For now I have changed Import/view/adminhtml/web/css/style.css

```
.pimgento-step .primary {
    float:left
}
```

So the button aligns with the uploaded file and is not over lapped.... then it works
![image](https://cloud.githubusercontent.com/assets/13618973/17988608/6fcb4858-6b7b-11e6-9456-0d871325411c.png)

Now just need to figure out why it does not import Chinese (cn_ZH)....

Versions Magento 2.1.0 PimGento2 latest Akeneo 1.5 Chrome  52.0.2743.116

**Comment by sammarcus** [comment]
good find. I made a fix that should at least solve the issue in #63.
