### ISSUE TITLE
queries don't work when using a table prefix in magento installation

### ISSUE THREAD

**Issue by nzidol** [Agence-DnD/PIMGento-2#55]
![image](https://cloud.githubusercontent.com/assets/13618973/18040069/9bdcd0a4-6dfd-11e6-8fb1-cc61ef51bb8b.png)
![image](https://cloud.githubusercontent.com/assets/13618973/18040075/aef1aa98-6dfd-11e6-8131-cbd3124aad46.png)
![image](https://cloud.githubusercontent.com/assets/13618973/18040080/ba7d04e8-6dfd-11e6-8694-73fabf1a7c98.png)

**Comment by torhoehn** [comment]
It's fixed now: #135
