### ISSUE TITLE
File upload POST request 500'ing

### ISSUE THREAD

**Issue by sammarcus** [Agence-DnD/PIMGento-2#6]
The module was installed via Composer into a Magento 2.0.2 environment. When I attempt to upload the file after clicking the "Import" button, nothing is outputted in the log. Upon further inspection I discovered the `POST` request is receiving a 500 response.

![image](https://cloud.githubusercontent.com/assets/8689264/14545558/c4965dc2-026d-11e6-82a8-c776cf59b182.png)

Where can I start to debug this? I initially suspected this is occuring because it cannot write to the directory it needs to write to so that the file is temporarily saved for processing by PIMGento, but I am not sure where that location is.

![image](https://cloud.githubusercontent.com/assets/8689264/14545903/8f4c12b8-026f-11e6-9486-944364f2c29b.png)

Here is the payload:
```
Content-Disposition: form-data; name="file"; filename="PIMcategories.csv"
Content-Type: text/csv
```

Here is the actual header itself:
```
{"name":"PIMcategories.csv","type":"text\/csv","error":0,"size":123,"file":"PIMcategories_1.csv"}
```

cc @magentix 

Thanks for the help!

**Comment by sammarcus** [comment]
I was able to find the location where the file is kept after upload: `var/import/pimgento`

I was surprised to see every CSV I had attempted to import was safely stored in this directory. So, it is having no issue writing to this directory as the files are all there. Now I am very confused and do not know why I am getting a 500 after it uploads the file. Please help me, DnD.

**Comment by DnD-Barracuda** [comment]
@magentix will look at your issue next friday.
Regards,
Dn'D

**Comment by magentix** [comment]
Hi sammarcus,

Errors 500 are generally stored in apache error log file. Can you give us your error log report ?

(/var/log/apache2/error.log or /var/log/httpd/error_log).

Regards.

**Comment by magentix** [comment]
@sammarcus: have you find a solution to solve this issue?

**Comment by magentix** [comment]
@sammarcus: can we close this issue?

**Comment by sammarcus** [comment]
Hi, thanks very much for the help, sorry about the delay, there were many environment related problems related to this that took some time to sort through but was eventually able to resolve. The 500'ing was a strange manifestation of a dependency issue, among others. This particular issue is no longer occurring so I am closing. Thank you!
