### ISSUE TITLE
Empty value in dropdown

### ISSUE THREAD

**Issue by Atomschinken** [Agence-DnD/PIMGento-2#64]
Hi,

when selecting a value from a dropdown for a product, it is correctly imported in Magento.
Now switch back the value to "nothing" in Akeneo and reimport. The value in Magento is not changing.

I would expect that it changes back to "noting", too.

Regards,

**Comment by jonathansayag** [comment]
Hi,

This is due to https://github.com/Agence-DnD/PIMGento-2/blob/master/Entities/Model/ResourceModel/Entities.php#L392 which apply a condition to trim the attribute value.

So, the question could be : do we need this trim or not ?

Best

**Comment by Atomschinken** [comment]
Fixed with #120
