### ISSUE TITLE
Command line imports

### ISSUE THREAD

**Issue by SirBigoo** [Agence-DnD/PIMGento-2#7]
Hi guys,

I see in the roadmap that there is a ```Command line tool (bin/magento) options for imports``` item.

Is it currently in development or not ?

Thanks.

**Comment by magentix** [comment]
Hi,

This is in development. Team are working on it.

**Comment by magentix** [comment]
Command line tool has been added in last release (100.0.5).

**Example:**
```shell
php bin/magento pimgento:import --code=product --file=product.csv
```
