### ISSUE TITLE
Variant Groups not all child are added

### ISSUE THREAD

**Issue by julienanquetil** [Agence-DnD/PIMGento-2#70]
Hi,

Did someone already got this issue.

In my Akeneo export I got several groups.

For example group shirt with 200 sku linked to it (same value in groups column in csv file) and all axis are OK

But in my magento "configurable item" i got only 150 sku.

Didn't know why there is some miss like that...

Thanks

**Comment by tkn98** [comment]
Do you have numeric SKUs? (strings that could be interpreted as numbers?). And do you have duplicate SKUs? There can produce some unexpected results in Magento 2.

**Comment by julienanquetil** [comment]
yes exactly, our sku is fully numeric for that products but without duplicates (in Akeneo  or Magento).
We have other product with dash/ hyphen but didn't try if i get the same result.
Does the wrong part is on Magento ? or Pimgento ?

Tahnks

**Comment by tkn98** [comment]
First of all there is at least one part wrong in Magento 2 with numeric SKUs. The upstream issue is: https://github.com/magento/magento2/pull/5859 - This reported issue merely affects performance, not data-loss.

You can try if it makes a difference or check with a debugger where the data gets lost. I'd say that's the best way to follow it and/or create a scenario that can be easily reproduced.

**Comment by julienanquetil** [comment]
I make a "quick & dirty" fix : add entity id in db by hand and it's working because we are in prod and we can't spend times to find where it's wrong "online". We will try to find what's wrong before the next "release" of the website.

Thanks for your comment (and issue ;) )

**Comment by tkn98** [comment]
Great to read you found a way to work around the issue. Didn't know you can handle it by setting the entity ids.
