### ISSUE TITLE
Akeneo 1.6 support

### ISSUE THREAD

**Issue by tkn98** [Agence-DnD/PIMGento-2#72]
Similar as in #2 for Akeneo 1.5 I wanted to ask about the state of PIMGento-2 compatibility with Akeneo 1.6.

The readme so far does not state anything about Akeneo in that version 1.6, last mentioned version is 1.5.

### Background

We'd like to use PIMGento-2 in a Akeneo 1.6 based project but so far (because auf PIMGento-2) we're using Akeneo 1.5 because it's documented that way in the readme.

### References:

* #2
* https://github.com/Agence-DnD/PIMGento/issues/140
* https://github.com/akeneo-labs/EnhancedConnectorBundle

**Comment by tdgroot** [comment]
According to commit [bad5de489](https://github.com/Agence-DnD/PIMGento-2/commit/bad5de489d38f7ee276a58040cf1c5340f07ebdf) the module is compatible with Akeneo >= 1.3, it seems.
