### ISSUE TITLE
Import de catégorie - noms non affichés dans l'arbre

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#8]
Sur un magento 2 vierge, j'ai associé le store-view default à la locale fr_fr

Lors de l'import du fichier de test suivant : 
> code;parent;label-fr_FR
> master;;Vêtements
> tshirts;master;T-Shirts
> pants;master;Pantalons

Aucun nom de catégories n'est affichée dans l'arbre : 
![screenshot-m2modules lxc 2016-05-06 15-15-51](https://cloud.githubusercontent.com/assets/10595905/15074116/87f76136-139d-11e6-8bab-711fd7a1b1d9.png)

**Comment by spipu** [comment]
Il semble que vous ayez oublié d'enregistrer une valeur dans le store 0. Peut-être cela se produit si aucun store EN n'est envoyé par Akeneo ?

```
select attribute_id, backend_type from eav_attribute where entity_type_id=3 and attribute_code = 'name';
+--------------+--------------+
| attribute_id | backend_type |
+--------------+--------------+
|           42 | varchar      |
+--------------+--------------+

select * from catalog_category_entity_varchar where attribute_id=42;
+----------+--------------+----------+-----------+------------------+
| value_id | attribute_id | store_id | entity_id | value            |
+----------+--------------+----------+-----------+------------------+
|        1 |           42 |        0 |         1 | Root Catalog     |
|        2 |           42 |        0 |         2 | Default Category |
|      234 |           42 |        1 |        50 | Vêtements        |
|      235 |           42 |        1 |        43 | T-Shirts         |
|      236 |           42 |        1 |        44 | Pantalons        |
+----------+--------------+----------+-----------+------------------+
```

**Comment by spipu** [comment]
Pour info, j'ai testé en rajoutant la locale en_US dans Akeneo, et là le store 0 a bien été enregistré en BDD

```
code;parent;label-en_US;label-fr_FR
master;;Clothing;Vêtements
tshirts;master;T-Shirts;T-Shirts
pants;master;Pants;Pantalons
```

**Comment by spipu** [comment]
Infos Techniques : 
- Debian  Jessie
- Magento CE 2.0.5
- Akeneo EE 1.5.2

**Comment by christophednd** [comment]
Salut Laurent,
Merci pour tes retours, on va regarder ça.
Si de ton coté, tu as une piste ou la solution, n'hésite pas à nous faire un PR ;)
Pimgento2 est volontairement Open source pour que la communauté et des experts techniques  contribuent à son évolution.
à bientôt
Christophe

**Comment by spipu** [comment]
(pour info, ce pb n'est pas lié au format d'export, car le bundle EnhancedConnectorBundle ne modifie pas le format d'export des catégories)

**Comment by spipu** [comment]
Ce n'est pas un bug mais un pb de configuration de ma part : Dans Magento 2, il faut indiquer dans le scope global que la local à utiliser est "fr_FR".

je ferme cet issue
