### ISSUE TITLE
Cant connect pimgento2 to magento2 via composer

### ISSUE THREAD

**Issue by SaaqibBhat** [Agence-DnD/PIMGento-2#81]
Im trying to install the pimgento2 connector via composer. 

**composer.json file** 

{
         "description": "Module Pimgento for Magento 2",

    "repositories": [
        {
            "url": "https://github.com/Agence-DnD/PIMGento-2.git",
            "type": "git"
        }
    ],
        "minimum-stability": "dev",

        "require": {
        "php":"~5.5.0|~5.6.0|~7.0.0",
        "magento/framework":"*",
        "magento/module-backend":"*",
        "magento/module-catalog":"*",
        "magento/module-eav":"*",
        "magento/module-store":"*",
        "agencednd/module-pimgento":"^100.1"
  },
        "type": "magento2-module",
         "version": "100.1.1",
        "license": [
        "OSL-3.0",
        "AFL-3.0"
  ]

}

**these are the errors im getting** 
command 1:  composer require agencednd/module/pimgento
command 2: composer require agencednd/module/pimgento:~"100.1.1"

![error1](https://cloud.githubusercontent.com/assets/12715229/21757644/7142c662-d664-11e6-8efb-c032f57cba13.PNG)
![error2](https://cloud.githubusercontent.com/assets/12715229/21757645/71432c42-d664-11e6-8dc6-b4e13664e724.PNG)

please assist
thanks

**Comment by coresh** [comment]
Changing the composer.json line:

"minimum-stability": "alpha", -> "minimum-stability": "dev", 

helped for me
