### ISSUE TITLE
pimgento:import --code=category SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row

### ISSUE THREAD

**Issue by coresh** [Agence-DnD/PIMGento-2#83]
$ bin/magento --version
    Magento CLI version 2.1.3

    $ php -v
    PHP 7.0.14 (cli) (built: Dec  7 2016 10:01:29) ( NTS )
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
        with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

    $ bin/magento pimgento:import --code=category --file=/path/tmp/import/test_categories__small.csv
    [09:53:36] Create temporary table
    [09:53:36] completed
    [09:53:36] Fill temporary table
    [09:53:36] 1 line(s) found
    [09:53:36] Match code with Magento ID
    [09:53:36] completed
    [09:53:37] Create URL key
    [09:53:37] completed
    [09:53:37] Create structure
    [09:53:37] completed
    [09:53:37] Create position
    [09:53:37] completed
    [09:53:37] Create and update category entities
    [09:53:37] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`m213eeCht`.`catalog_category_entity`, CONSTRAINT `CAT_CTGR_ENTT_ENTT_ID_SEQUENCE_CAT_CTGR_SEQUENCE_VAL` FOREIGN KEY (`entity_id`) REFERENCES `sequence_catalog_category` (`sequence_value`) ON ), query was: INSERT INTO `catalog_category_entity` (`entity_id`, `attribute_set_id`, `parent_id`, `updated_at`, `path`, `position`, `level`, `children_count`) SELECT `tmp_pimgento_entities_category`.`_entity_id` AS `entity_id`, 3 AS `attribute_set_id`, `tmp_pimgento_entities_category`.`parent_id`, now() AS `updated_at`, `tmp_pimgento_entities_category`.`path`, `tmp_pimgento_entities_category`.`position`, `tmp_pimgento_entities_category`.`level`, 0 AS `children_count` FROM `tmp_pimgento_entities_category` ON DUPLICATE KEY UPDATE `entity_id` = VALUES(`entity_id`), `attribute_set_id` = VALUES(`attribute_set_id`), `parent_id` = VALUES(`parent_id`), `updated_at` = VALUES(`updated_at`), `path` = VALUES(`path`), `position` = VALUES(`position`), `level` = VALUES(`level`), `children_count` = VALUES(`children_count`)

### content of file 'test_categories__small.csv':
    code;parent;label-de_DE;label-en_US;label-fr_FR
    master;;Hauptkatalog;"Master catalog";"Catalogue principal"

### Full mysql general log:
    /usr/libexec/mysqld, Version: 10.1.20-MariaDB (MariaDB Server). started with:
    Tcp port: 0  Unix socket: /var/lib/mysql/mysql.sock
    Time                 Id Command    Argument
    170118 10:46:01	    2 Connect	dbU7DoqXO0EU6AuQONe8GQX234B85Uiz@localhost as anonymous on magento2db
                        2 Query	SET SQL_MODE=''
                        2 Query	SET time_zone = '+00:00'
                        2 Query	SET NAMES utf8
                        2 Query	SELECT `flag`.* FROM `flag` WHERE (`flag`.`flag_code`='staging')
                        2 Query	SELECT `store`.* FROM `store` WHERE (`store`.`store_id`='1') ORDER BY `sort_order` ASC
                        2 Query	START TRANSACTION
                        2 Query	INSERT INTO `pimgento_import_log` (`identifier`, `code`, `name`, `file`, `status`, `created_at`) VALUES ('587f47693093a', 'category', 'Categories', '/m2/tmp/import/test_categories__small.csv', '3', '2017-01-18 10:46:01')
                        2 Query	COMMIT
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`) VALUES ('32', '587f47693093a', '0', 'start', '[10:46:01] Start import')
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`, `continue`, `status`) VALUES ('32', '587f47693093a', '0', 'start', '[10:46:01] Import id: 587f47693093a', '1', '1')
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`) VALUES ('32', '587f47693093a', '1', 'createTable', '[10:46:01] Create temporary table')
                        2 Query	DROP TABLE IF EXISTS `tmp_pimgento_entities_category`
                        2 Query	CREATE TABLE IF NOT EXISTS `tmp_pimgento_entities_category` (
    `code` text NULL COMMENT 'code' ,
    `parent` text NULL COMMENT 'parent' ,
    `label-de_DE` text NULL COMMENT 'label-de_DE' ,
    `label-en_US` text NULL COMMENT 'label-en_US' ,
    `label-fr_FR` text NULL COMMENT 'label-fr_FR' ,
    `_entity_id` int NULL COMMENT 'Entity Id' ,
    `_is_new` smallint NULL default '0' COMMENT 'Is New' ,
    UNIQUE `UNIQUE_ENTITY_ID` (`_entity_id`)
    ) COMMENT='tmp_pimgento_entities_category' ENGINE=innodb charset=utf8 COLLATE=utf8_general_ci
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`, `continue`, `status`) VALUES ('32', '587f47693093a', '1', 'createTable', '[10:46:01] completed', '1', '1')
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`) VALUES ('32', '587f47693093a', '2', 'insertData', '[10:46:01] Fill temporary table')
                        2 Query	LOAD DATA LOCAL INFILE '/tmp/test_categories__small.csv' REPLACE
                INTO TABLE tmp_pimgento_entities_category
                CHARACTER SET UTF8
                FIELDS TERMINATED BY ';'
                OPTIONALLY ENCLOSED BY '"'
                LINES TERMINATED BY '\n'
                IGNORE 1 LINES
                        2 Query	SELECT COUNT(*) FROM `tmp_pimgento_entities_category`
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`, `continue`, `status`) VALUES ('32', '587f47693093a', '2', 'insertData', '[10:46:01] 1 line(s) found', '1', '1')
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`) VALUES ('32', '587f47693093a', '3', 'matchEntity', '[10:46:01] Match code with Magento ID')
                        2 Query	DELETE FROM `tmp_pimgento_entities_category` WHERE (code = '')
                        2 Query	UPDATE `tmp_pimgento_entities_category` t
                SET `_entity_id` = (
                    SELECT `entity_id` FROM `pimgento_entities` c
                    WHERE t.`code` = c.`code`
                        AND c.`import` = "category"
                )
                        2 Query	SHOW TABLE STATUS LIKE "catalog_category_entity"
                        2 Query	SET @id = 3
                        2 Query	UPDATE `tmp_pimgento_entities_category` SET `_entity_id` = @id := @id + 1, `_is_new` = 1 WHERE (_entity_id IS NULL)
                        2 Query	INSERT IGNORE INTO `pimgento_entities` (`import`, `code`, `entity_id`) SELECT 'category' AS `import`, `tmp_pimgento_entities_category`.`code`, `tmp_pimgento_entities_category`.`_entity_id` AS `entity_id` FROM `tmp_pimgento_entities_category` WHERE (_is_new = 1)
                        2 Query	SELECT COUNT(*) FROM `tmp_pimgento_entities_category` WHERE (_is_new = 1)
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`, `continue`, `status`) VALUES ('32', '587f47693093a', '3', 'matchEntity', '[10:46:01] completed', '1', '1')
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`) VALUES ('32', '587f47693093a', '4', 'setUrlKey', '[10:46:01] Create URL key')
                        2 Query	SELECT `store_website`.* FROM `store_website` WHERE (`store_website`.`website_id`='1')
                        2 Query	SELECT `store_website`.* FROM `store_website` WHERE (`store_website`.`website_id`='0')
                        2 Query	SELECT `store_website`.* FROM `store_website` WHERE (`store_website`.`website_id`='2')
                        2 Query	DESCRIBE `tmp_pimgento_entities_category`
                        2 Query	ALTER TABLE `tmp_pimgento_entities_category` ADD COLUMN `url_key-en_US` VARCHAR(255) NOT NULL DEFAULT ""
                        2 Query	SELECT `tmp_pimgento_entities_category`.`_entity_id` AS `entity_id`, `tmp_pimgento_entities_category`.`label-en_US` AS `name` FROM `tmp_pimgento_entities_category`
                        2 Query	UPDATE `tmp_pimgento_entities_category` SET `url_key-en_US` = 'master-catalog' WHERE (_entity_id = '4')
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`, `continue`, `status`) VALUES ('32', '587f47693093a', '4', 'setUrlKey', '[10:46:01] completed', '1', '1')
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`) VALUES ('32', '587f47693093a', '5', 'setStructure', '[10:46:01] Create structure')
                        2 Query	DESCRIBE `tmp_pimgento_entities_category`
                        2 Query	ALTER TABLE `tmp_pimgento_entities_category` ADD COLUMN `level` INT(11) NOT NULL DEFAULT 0
                        2 Query	DESCRIBE `tmp_pimgento_entities_category`
                        2 Query	ALTER TABLE `tmp_pimgento_entities_category` ADD COLUMN `path` VARCHAR(255) NOT NULL DEFAULT ""
                        2 Query	DESCRIBE `tmp_pimgento_entities_category`
                        2 Query	ALTER TABLE `tmp_pimgento_entities_category` ADD COLUMN `parent_id` INT(11) NOT NULL DEFAULT 0
                        2 Query	UPDATE `tmp_pimgento_entities_category` SET `level` = '1', `path` = CONCAT(1, "/", `_entity_id`), `parent_id` = '1' WHERE (parent = "")
                        2 Query	DESCRIBE `tmp_pimgento_entities_category`
                        2 Query	ALTER TABLE `tmp_pimgento_entities_category` ADD COLUMN `_url_rewrite-en_US` VARCHAR(255) NOT NULL DEFAULT ""
                        2 Query	UPDATE `tmp_pimgento_entities_category` c1
                    INNER JOIN `tmp_pimgento_entities_category` c2 ON c2.`code` = c1.`parent`
                    SET c1.`_url_rewrite-en_US` =
                        TRIM(BOTH "/" FROM CONCAT(c2.`_url_rewrite-en_US`, "/", c1.`url_key-en_US`)),
                        c1.`level` = c2.`level` + 1,
                        c1.`path` = CONCAT(c2.`path`, "/", c1.`_entity_id`),
                        c1.`parent_id` = c2.`_entity_id`
                    WHERE c1.`level` <= c2.`level` - 1
                        2 Query	UPDATE `tmp_pimgento_entities_category` c1
                    INNER JOIN `tmp_pimgento_entities_category` c2 ON c2.`code` = c1.`parent`
                    SET c1.`_url_rewrite-en_US` =
                        TRIM(BOTH "/" FROM CONCAT(c2.`_url_rewrite-en_US`, "/", c1.`url_key-en_US`)),
                        c1.`level` = c2.`level` + 1,
                        c1.`path` = CONCAT(c2.`path`, "/", c1.`_entity_id`),
                        c1.`parent_id` = c2.`_entity_id`
                    WHERE c1.`level` <= c2.`level` - 1
                        2 Query	UPDATE `tmp_pimgento_entities_category` c1
                    INNER JOIN `tmp_pimgento_entities_category` c2 ON c2.`code` = c1.`parent`
                    SET c1.`_url_rewrite-en_US` =
                        TRIM(BOTH "/" FROM CONCAT(c2.`_url_rewrite-en_US`, "/", c1.`url_key-en_US`)),
                        c1.`level` = c2.`level` + 1,
                        c1.`path` = CONCAT(c2.`path`, "/", c1.`_entity_id`),
                        c1.`parent_id` = c2.`_entity_id`
                    WHERE c1.`level` <= c2.`level` - 1
                        2 Query	UPDATE `tmp_pimgento_entities_category` c1
                    INNER JOIN `tmp_pimgento_entities_category` c2 ON c2.`code` = c1.`parent`
                    SET c1.`_url_rewrite-en_US` =
                        TRIM(BOTH "/" FROM CONCAT(c2.`_url_rewrite-en_US`, "/", c1.`url_key-en_US`)),
                        c1.`level` = c2.`level` + 1,
                        c1.`path` = CONCAT(c2.`path`, "/", c1.`_entity_id`),
                        c1.`parent_id` = c2.`_entity_id`
                    WHERE c1.`level` <= c2.`level` - 1
                        2 Query	UPDATE `tmp_pimgento_entities_category` c1
                    INNER JOIN `tmp_pimgento_entities_category` c2 ON c2.`code` = c1.`parent`
                    SET c1.`_url_rewrite-en_US` =
                        TRIM(BOTH "/" FROM CONCAT(c2.`_url_rewrite-en_US`, "/", c1.`url_key-en_US`)),
                        c1.`level` = c2.`level` + 1,
                        c1.`path` = CONCAT(c2.`path`, "/", c1.`_entity_id`),
                        c1.`parent_id` = c2.`_entity_id`
                    WHERE c1.`level` <= c2.`level` - 1
                        2 Query	UPDATE `tmp_pimgento_entities_category` c1
                    INNER JOIN `tmp_pimgento_entities_category` c2 ON c2.`code` = c1.`parent`
                    SET c1.`_url_rewrite-en_US` =
                        TRIM(BOTH "/" FROM CONCAT(c2.`_url_rewrite-en_US`, "/", c1.`url_key-en_US`)),
                        c1.`level` = c2.`level` + 1,
                        c1.`path` = CONCAT(c2.`path`, "/", c1.`_entity_id`),
                        c1.`parent_id` = c2.`_entity_id`
                    WHERE c1.`level` <= c2.`level` - 1
                        2 Query	UPDATE `tmp_pimgento_entities_category` c1
                    INNER JOIN `tmp_pimgento_entities_category` c2 ON c2.`code` = c1.`parent`
                    SET c1.`_url_rewrite-en_US` =
                        TRIM(BOTH "/" FROM CONCAT(c2.`_url_rewrite-en_US`, "/", c1.`url_key-en_US`)),
                        c1.`level` = c2.`level` + 1,
                        c1.`path` = CONCAT(c2.`path`, "/", c1.`_entity_id`),
                        c1.`parent_id` = c2.`_entity_id`
                    WHERE c1.`level` <= c2.`level` - 1
                        2 Query	UPDATE `tmp_pimgento_entities_category` c1
                    INNER JOIN `tmp_pimgento_entities_category` c2 ON c2.`code` = c1.`parent`
                    SET c1.`_url_rewrite-en_US` =
                        TRIM(BOTH "/" FROM CONCAT(c2.`_url_rewrite-en_US`, "/", c1.`url_key-en_US`)),
                        c1.`level` = c2.`level` + 1,
                        c1.`path` = CONCAT(c2.`path`, "/", c1.`_entity_id`),
                        c1.`parent_id` = c2.`_entity_id`
                    WHERE c1.`level` <= c2.`level` - 1
                        2 Query	UPDATE `tmp_pimgento_entities_category` c1
                    INNER JOIN `tmp_pimgento_entities_category` c2 ON c2.`code` = c1.`parent`
                    SET c1.`_url_rewrite-en_US` =
                        TRIM(BOTH "/" FROM CONCAT(c2.`_url_rewrite-en_US`, "/", c1.`url_key-en_US`)),
                        c1.`level` = c2.`level` + 1,
                        c1.`path` = CONCAT(c2.`path`, "/", c1.`_entity_id`),
                        c1.`parent_id` = c2.`_entity_id`
                    WHERE c1.`level` <= c2.`level` - 1
                        2 Query	UPDATE `tmp_pimgento_entities_category` c1
                    INNER JOIN `tmp_pimgento_entities_category` c2 ON c2.`code` = c1.`parent`
                    SET c1.`_url_rewrite-en_US` =
                        TRIM(BOTH "/" FROM CONCAT(c2.`_url_rewrite-en_US`, "/", c1.`url_key-en_US`)),
                        c1.`level` = c2.`level` + 1,
                        c1.`path` = CONCAT(c2.`path`, "/", c1.`_entity_id`),
                        c1.`parent_id` = c2.`_entity_id`
                    WHERE c1.`level` <= c2.`level` - 1
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`, `continue`, `status`) VALUES ('32', '587f47693093a', '5', 'setStructure', '[10:46:01] completed', '1', '1')
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`) VALUES ('32', '587f47693093a', '6', 'setPosition', '[10:46:01] Create position')
                        2 Query	DESCRIBE `tmp_pimgento_entities_category`
                        2 Query	ALTER TABLE `tmp_pimgento_entities_category` ADD COLUMN `position` INT(11) NOT NULL DEFAULT 0
                        2 Query	SELECT `tmp_pimgento_entities_category`.`_entity_id` AS `entity_id`, `tmp_pimgento_entities_category`.`parent_id` FROM `tmp_pimgento_entities_category`
                        2 Query	SELECT MAX(`position`) + 1 AS `position` FROM `tmp_pimgento_entities_category` WHERE (parent_id = '1') GROUP BY `parent_id`
                        2 Query	UPDATE `tmp_pimgento_entities_category` SET `position` = '1' WHERE (_entity_id = '4')
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`, `continue`, `status`) VALUES ('32', '587f47693093a', '6', 'setPosition', '[10:46:01] completed', '1', '1')
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`) VALUES ('32', '587f47693093a', '7', 'createEntities', '[10:46:01] Create and update category entities')
                        2 Query	INSERT INTO `catalog_category_entity` (`entity_id`, `attribute_set_id`, `parent_id`, `updated_at`, `path`, `position`, `level`, `children_count`) SELECT `tmp_pimgento_entities_category`.`_entity_id` AS `entity_id`, 3 AS `attribute_set_id`, `tmp_pimgento_entities_category`.`parent_id`, now() AS `updated_at`, `tmp_pimgento_entities_category`.`path`, `tmp_pimgento_entities_category`.`position`, `tmp_pimgento_entities_category`.`level`, 0 AS `children_count` FROM `tmp_pimgento_entities_category` ON DUPLICATE KEY UPDATE `entity_id` = VALUES(`entity_id`), `attribute_set_id` = VALUES(`attribute_set_id`), `parent_id` = VALUES(`parent_id`), `updated_at` = VALUES(`updated_at`), `path` = VALUES(`path`), `position` = VALUES(`position`), `level` = VALUES(`level`), `children_count` = VALUES(`children_count`)
                        2 Query	SELECT `pimgento_import_log`.* FROM `pimgento_import_log` WHERE (`pimgento_import_log`.`identifier`='587f47693093a')
                        2 Query	START TRANSACTION
                        2 Query	UPDATE `pimgento_import_log` SET `status` = '2' WHERE (log_id='32')
                        2 Query	COMMIT
                        2 Query	INSERT INTO `pimgento_import_log_step` (`log_id`, `identifier`, `number`, `method`, `message`, `continue`, `status`) VALUES ('32', '587f47693093a', '7', 'createEntities', '[10:46:01] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento2db`.`catalog_category_entity`, CONSTRAINT `CAT_CTGR_ENTT_ENTT_ID_SEQUENCE_CAT_CTGR_SEQUENCE_VAL` FOREIGN KEY (`entity_id`) REFERENCES `sequence_catalog_category` (`sequence_value`) ON ), query was: INSERT INTO `catalog_category_entity` (`entity_id`, `attribute_set_id`, `parent_id`, `updated_at`, `path`, `position`, `level`, `children_count`) SELECT `tmp_pimgento_entities_category`.`_entity_id` AS `entity_id`, 3 AS `attribute_set_id`, `tmp_pimgento_entities_category`.`parent_id`, now() AS `updated_at`, `tmp_pimgento_entities_category`.`path`, `tmp_pimgento_entities_category`.`position`, `tmp_pimgento_entities_category`.`level`, 0 AS `children_count` FROM `tmp_pimgento_entities_category` ON DUPLICATE KEY UPDATE `entity_id` = VALUES(`entity_id`), `attribute_set_id` = VALUES(`attribute_set_id`), `parent_id` = VALUES(`parent_id`), `updated_at` = VALUES(`updated_at`), `path` = VALUES(`path`), `position` = VALUES(`position`), `level` = VALUES(`level`), `children_count` = VALUES(`children_count`)', '0', '0')
                        2 Quit

**Comment by bobbyn** [comment]
I had a similar problem yesterday and the problem was caused by inconsistent data - missing attribute_set. So I would suggest check categories in your case and if needed reimport, reindex, clean cache and then reimport product after check data.

**Comment by coresh** [comment]
moved to [https://github.com/Agence-DnD/PIMGento-2/issues/85](url)

**Comment by sammarcus** [comment]
@coresh if you share your CSV that would be helpful 👍

**Comment by coresh** [comment]
content of file 'test_categories__small.csv':

code;parent;label-de_DE;label-en_US;label-fr_FR
master;;Hauptkatalog;"Master catalog";"Catalogue principal"
