### ISSUE TITLE
MySQL error 1148 during import in a Docker env

### ISSUE THREAD

**Issue by guillaume-netapsys** [Agence-DnD/PIMGento-2#87]
Hello,

First of all I'm working with : 
- Magento 2.1.3
- Akeneo 1.6.8
- EnhancedConnectorBundle 1.3.x
- PIMGento 100.1.1

My working env is a Docker env with a web container and a database one. So we can consider that those entities are not on the same server. All the following commands are submited from the web container.

I'm trying to import a file generated by Akeneo with a command line.

`php bin/magento pimgento:import --code=product --file=products_export_en_US_ecommerce_2017-01-19_08_38_52.csv`

I'm getting the following : 

```
[08:02:20] Start import
[08:02:20] Import id: 5881c40c17a5d
[08:02:20] Create temporary table
[08:02:20] completed
[08:02:20] Fill temporary table
[08:02:20] SQLSTATE[42000]: Syntax error or access violation: 1148 The used command is not allowed with this MySQL version, query was: LOAD DATA LOCAL INFILE '/tmp/products_export_en_US_ecommerce_2017-01-19_08_38_52.csv' REPLACE
              INTO TABLE tmp_pimgento_entities_product
              CHARACTER SET UTF8
              FIELDS TERMINATED BY ';'
              OPTIONALLY ENCLOSED BY '"'
              LINES TERMINATED BY '\n'
              IGNORE 1 LINES;
```

My env.php file contains the following line with the db connection params : 

`'driver_options' => array(PDO::MYSQL_ATTR_LOCAL_INFILE => true),`

My local_infile parameter is correctly setted : 

```
mysql> SHOW GLOBAL VARIABLES LIKE 'local_infile';<br/>
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| local_infile  | ON    |
+---------------+-------+
1 row in set (0.00 sec)
```

For a test purpose MySQL user is able to do everything including FILE handling.

In the Magento config I've configured the "Load Local Data" to YES (the case when the database is not on the same server than the one who handle PHP).

After multiple tests I've managed to pass the query to MySQL by doing the following : 

`mysql --local-infile=1 -u <my_user> -p -h <my_db_host> -e "LOAD DATA LOCAL INFILE '/tmp/products_export_en_US_ecommerce_2017-01-19_08_38_52.csv' REPLACE INTO TABLE tmp_pimgento_entities_product CHARACTER SET UTF8 FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '""' LINES TERMINATED BY '\n' IGNORE 1 LINES;" <my_db_name>`

So the only difference here is `--local-infile=1`.
I thought it was the point of `'driver_options' => array(PDO::MYSQL_ATTR_LOCAL_INFILE => true),` to edit the MySQL connection object in order to handle the local infile parameter.

Can somebody give me some feedback or some hints to help me understand why it's not correctly working right now ?
Thank you.

**Comment by oliverde8** [comment]
You need to change your Pimgento configuration not to use Data in File but normal inserts. Lot of hosting won't allow data in file anyways and using the option By 1000 Rows is quite fast as well.

* Stores > Configuration
* Catalog > Pimgento > General > Data insert method 

And select **By 1000 Rows**

**Comment by guillaume-netapsys** [comment]
That is my backup strategy yes. It's not solving the main problem.
I'm working locally, I can handle every aspect of my environment, so I don't understand why I'm not able to use the "infile" method.

**Comment by guillaume-netapsys** [comment]
Hello,
The problem was the php driver for MySQL.
I used php5-mysql and after a switch to php5-mysqlnd, the "LOCALE INFILE" parameter is now taken into account.
Thank you for your help.
