### ISSUE TITLE
mauvais message d'erreur

### ISSUE THREAD

**Issue by spipu** [Agence-DnD/PIMGento-2#9]
J'ai eu le message d'erreur suivant durant un test d'import : 
> Colinne label introuvable

Colinne => Colonne ;)

**Comment by christophednd** [comment]
Salut Laurent,
Merci pour tes retours, on va regarder ça.
Si de ton coté, tu as une piste ou la solution, n'hésite pas à nous faire un PR ;)
Pimgento2 est volontairement Open source pour que la communauté et des experts techniques  contribuent à son évolution.
à bientôt
Christophe

**Comment by magentix** [comment]
Hi Laurent,

This issue has been fixed in last release (100.0.7).

Regards,
Matthieu

**Comment by spipu** [comment]
Thx a lot for this new release !

I will test it on monday.

**Comment by spipu** [comment]
thanks !
