### ISSUE TITLE
Useless increment on the same URL keys for categories across multiple store views

### ISSUE THREAD

**Issue by shavounet** [Agence-DnD/PIMGento-2#95]
Test case:
- on a magento instance with 10+ store views (with different locales), I have imported the same category tree
- there is some redundancy for URL keys across store views (e.g. "sliver" is a generic name, and the same for every store view)
- import the categories from akeneo

Actual result:
- an increment (e.g. "-4") is appended on the URL keys, even if there is no conflict ; on the screenshot below, there is only one line per store view:
![selection_087](https://cloud.githubusercontent.com/assets/2323369/23610915/f197aaf8-0274-11e7-9c2c-f42a22cd88e2.png)

Expected:
- (at least) the increment should only be appended if there is more than one identical URL key ; see `\Pimgento\Category\Model\Factory\Import::setUrlKey`, with the `$increment` variable
- yet I think this not necessary, it would solve a lot of problems (such as #66) to use more closely the native method: `\Magento\CatalogUrlRewrite\Model\CategoryUrlPathGenerator::getUrlPathWithSuffix` ; it might induce a very small performance penalty, but it should be worth it

**Comment by shavounet** [comment]
Well the fix was easy... `\Pimgento\Category\Model\Factory\Import::setUrlKey`, line 119, move `$keys = [];` into the following store loop.

**Comment by magentix** [comment]
Hi,

Thanks for report. Fixed: 38012a73803bf2697a9036e9405207017ae08fdd
